# Generated by Django 4.0.4 on 2022-06-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_sku_alter_vouchercode_coupon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, default='GE30PRO6U0', editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='vouchercode',
            name='coupon_code',
            field=models.CharField(blank=True, default='VP43DXF4', max_length=8, unique=True),
        ),
    ]
